on:
  push:
    paths:
      - data/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint Data Files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Blox
        id: build
        uses: devrel-blox/github-action@v0.0.7
        with:
          directory: data

      - name: Output
        run: echo "Messages ${{ steps.build.outputs.messages }}"

      - name: Publish Blox
        uses: softprops/action-gh-release@v1
        with:
          files: data/out/data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
